/**
 * Dummy Cars Data
 * 
 * Sample car data for development and testing.
 * TODO: Replace with Supabase queries when connecting to the database.
 */

import { Car } from '@/types/car'

export const dummyCars: Car[] = [
  {
    id: '1',
    name: 'Toyota Corolla 2022',
    brand: 'Toyota',
    model: 'Corolla',
    year: 2022,
    plateNumber: 'TR-1234-AB',
    color: 'White',
    transmission: 'automatic',
    fuelType: 'petrol',
    seats: 5,
    dailyRate: 35,
    imageUrl: 'https://images.unsplash.com/photo-1606664515524-ed2f786a0ad6?w=800',
    status: 'available',
    mileage: 25000,
    description: 'Reliable and fuel-efficient sedan, perfect for city driving.',
    features: ['Air Conditioning', 'Bluetooth', 'USB Port', 'Backup Camera'],
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-11-20'),
  },
  {
    id: '2',
    name: 'Mercedes-Benz C-Class',
    brand: 'Mercedes-Benz',
    model: 'C-Class',
    year: 2023,
    plateNumber: 'TR-5678-CD',
    color: 'Black',
    transmission: 'automatic',
    fuelType: 'diesel',
    seats: 5,
    dailyRate: 75,
    imageUrl: 'https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?w=800',
    status: 'rented',
    mileage: 15000,
    description: 'Luxury sedan with premium features and exceptional comfort.',
    features: ['Leather Seats', 'Navigation', 'Sunroof', 'Premium Audio', 'Heated Seats'],
    createdAt: new Date('2024-02-10'),
    updatedAt: new Date('2024-11-22'),
  },
  {
    id: '3',
    name: 'BMW 3 Series',
    brand: 'BMW',
    model: '3 Series',
    year: 2023,
    plateNumber: 'TR-9012-EF',
    color: 'Blue',
    transmission: 'automatic',
    fuelType: 'petrol',
    seats: 5,
    dailyRate: 80,
    imageUrl: 'https://images.unsplash.com/photo-1555215695-3004980ad54e?w=800',
    status: 'available',
    mileage: 18000,
    description: 'Sporty luxury sedan with dynamic performance.',
    features: ['Sport Mode', 'Navigation', 'Parking Sensors', 'Adaptive Cruise Control'],
    createdAt: new Date('2024-03-05'),
    updatedAt: new Date('2024-11-21'),
  },
  {
    id: '4',
    name: 'Volkswagen Golf',
    brand: 'Volkswagen',
    model: 'Golf',
    year: 2021,
    plateNumber: 'TR-3456-GH',
    color: 'Gray',
    transmission: 'manual',
    fuelType: 'diesel',
    seats: 5,
    dailyRate: 30,
    imageUrl: 'https://images.unsplash.com/photo-1606664515524-ed2f786a0ad6?w=800',
    status: 'available',
    mileage: 45000,
    description: 'Compact and economical hatchback, great fuel efficiency.',
    features: ['Air Conditioning', 'Bluetooth', 'USB Port'],
    createdAt: new Date('2024-01-20'),
    updatedAt: new Date('2024-11-19'),
  },
  {
    id: '5',
    name: 'Audi A4',
    brand: 'Audi',
    model: 'A4',
    year: 2022,
    plateNumber: 'TR-7890-IJ',
    color: 'Silver',
    transmission: 'automatic',
    fuelType: 'diesel',
    seats: 5,
    dailyRate: 70,
    imageUrl: 'https://images.unsplash.com/photo-1606664515524-ed2f786a0ad6?w=800',
    status: 'maintenance',
    mileage: 32000,
    description: 'Premium sedan with advanced technology and comfort.',
    features: ['Virtual Cockpit', 'LED Headlights', 'Navigation', 'Parking Assist'],
    createdAt: new Date('2024-02-25'),
    updatedAt: new Date('2024-11-23'),
  },
  {
    id: '6',
    name: 'Tesla Model 3',
    brand: 'Tesla',
    model: 'Model 3',
    year: 2023,
    plateNumber: 'TR-1122-KL',
    color: 'White',
    transmission: 'automatic',
    fuelType: 'electric',
    seats: 5,
    dailyRate: 90,
    imageUrl: 'https://images.unsplash.com/photo-1560958089-b8a1929cea89?w=800',
    status: 'available',
    mileage: 12000,
    description: 'Cutting-edge electric vehicle with autopilot capabilities.',
    features: ['Autopilot', 'Premium Audio', 'Glass Roof', 'Supercharging', 'Mobile App'],
    createdAt: new Date('2024-04-01'),
    updatedAt: new Date('2024-11-23'),
  },
  {
    id: '7',
    name: 'Ford Focus',
    brand: 'Ford',
    model: 'Focus',
    year: 2020,
    plateNumber: 'TR-3344-MN',
    color: 'Red',
    transmission: 'manual',
    fuelType: 'petrol',
    seats: 5,
    dailyRate: 28,
    imageUrl: 'https://images.unsplash.com/photo-1606664515524-ed2f786a0ad6?w=800',
    status: 'available',
    mileage: 55000,
    description: 'Affordable and reliable compact car.',
    features: ['Air Conditioning', 'Bluetooth', 'USB Port'],
    createdAt: new Date('2024-01-10'),
    updatedAt: new Date('2024-11-18'),
  },
  {
    id: '8',
    name: 'Hyundai Tucson',
    brand: 'Hyundai',
    model: 'Tucson',
    year: 2023,
    plateNumber: 'TR-5566-OP',
    color: 'Black',
    transmission: 'automatic',
    fuelType: 'hybrid',
    seats: 5,
    dailyRate: 65,
    imageUrl: 'https://images.unsplash.com/photo-1606664515524-ed2f786a0ad6?w=800',
    status: 'available',
    mileage: 8000,
    description: 'Modern SUV with hybrid technology for efficiency.',
    features: ['Apple CarPlay', 'Android Auto', 'Lane Assist', 'Blind Spot Monitor', 'Panoramic Sunroof'],
    createdAt: new Date('2024-05-15'),
    updatedAt: new Date('2024-11-23'),
  },
]


